FROM python:3.9.9-slim-buster

# set directory
WORKDIR /home

COPY ./requirements.txt .

RUN apt-get update && apt-get upgrade -y \
    && pip install -r requirements.txt

# choose port
EXPOSE 8501

# start the app
CMD ["streamlit", "run", "src/iris-frontend.py"]

# # build the container
# docker build -t iris-frontend .

# # run the container
# docker run -p 8000:8000 iris-frontend

